name: TEST SECRETS

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SOME_NAME }}
        SUPER_SECRET1: 1111
      run: |
        echo $SUPER_SECRET
        echo $SUPER_SECRET1
    
